Adding Snapshot Strategy for Moxie
Airstack-xyz/snapshot-strategies pull request #1
Opened 2024-10-05 10:47 UTC by Hrishikesh-Thakkar

Changes proposed in this pull request:
- Adding a new snapshot strategy for Moxie

2024-10-08 08:14 UTC, 0xsarvesh requested changes

2024-10-08 08:14 UTC, 0xsarvesh commented on src/strategies/moxie/README.md
> +5. Liquidity Pool Contributions
staked fan tokens for wallet & vesting contracts.

2024-10-08 08:14 UTC, 0xsarvesh commented on src/strategies/moxie/index.ts
> +  const liquidityPoolSubgraphQuery = {
can we make parallel calls with portfolio subgraph

2024-10-08 08:14 UTC, 0xsarvesh commented on src/strategies/moxie/index.ts
> +  const multi = new Multicaller(network, provider, abi, { blockTag });
this can be parallel too

2024-10-09 09:53 UTC, 0xsarvesh reviewed
overall looks good, what happen if network call fails?

2024-10-09 10:45 UTC, sharathkrml approved these changes
LGTM

2024-10-09 13:25 UTC, merged